server:
  port: 8081

spring:
  application:
    name: activity-user-module
  config:
    import: optional:file:activity-user-module/.env.example[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5555/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
