server:
  port: 8081

spring:
  application:
    name: activity-user-module
  config:
    import: optinal:file:.env.example[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5555/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none